name: Check Clean Linux Build

on:
  push:
    paths:
      - 'linux'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Push to linux repository
      run: |
        cd linux
        git remote add myjjh https://github.com/jeochris/linux
        git push myjjh csi2115-f21
        cd ..
      
    - name: Download current linux
      run: wget -d https://github.com/jeochris/linux/archive/$(git rev-parse HEAD:linux).zip
    - name: Unzip linux
      run: unzip $(git rev-parse HEAD:linux).zip
    
    - name: Check file names
      run: ls
      
    - name: Install Dependencies
      run: ./install-deps.sh
