name: Check Clean Linux Build

on:
  push:
    paths:
      - 'linux'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Push to linux repository
      run: |
        cd linux
        git config --global user.name 'Jaehyun Jeon'
        git config --global user.email 'chris990126@gmail.com'
        git remote add myjjh https://github.com/jeochris/linux
        git fetch myjjh
        git log
        cd ..
      
