name: Check Clean Linux Build

on:
  push:
    paths:
      - 'linux'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Download linux repository
      run: wget https://github.com/jeochris/linux/archive/$(git rev-parse HEAD:linux).zip
      
    - name: Check file names
      run: ls
    
    - name: Unzip linux
      run: unzip $(git rev-parse HEAD:linux).zip
      
    - name: Check file names 2
      run: ls
      
      
